# Generated by Django 2.2 on 2020-05-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200527_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emailservice',
            new_name='emailservicemodel',
        ),
    ]
