# Generated by Django 2.2 on 2020-05-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200528_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailservicemodel',
            name='skill',
            field=models.CharField(max_length=50),
        ),
    ]
