# Generated by Django 2.2 on 2020-05-31 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200528_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailservicemodel',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Skill'),
        ),
    ]
