# Generated by Django 2.2 on 2020-06-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200601_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailservicemodel',
            name='skill',
            field=models.CharField(max_length=100),
        ),
    ]
