# Generated by Django 2.2 on 2020-06-01 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20200602_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailservicemodel',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Skill'),
        ),
    ]
