# Generated by Django 2.2 on 2020-06-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200602_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailservicemodel',
            name='skill',
            field=models.CharField(max_length=100),
        ),
    ]
