# Generated by Django 3.0.7 on 2020-06-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200623_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theory',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
