# Generated by Django 3.0.7 on 2020-06-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_userprofile_theory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailservicemodel',
            name='skill',
        ),
    ]
