# Generated by Django 3.0.7 on 2020-07-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
