# Generated by Django 3.0.7 on 2020-07-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_adminprofile_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.adminProfile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
