# Generated by Django 3.0.7 on 2020-07-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_centure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centure',
            name='centure_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
