# Generated by Django 2.2 on 2020-08-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20200728_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='social_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.social_media'),
        ),
    ]
