# Generated by Django 2.2 on 2020-08-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_auto_20200801_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='social_media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysite.social_media'),
        ),
    ]
