# Generated by Django 2.2 on 2020-08-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20200801_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_media',
            name='bale',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='github',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='instagram',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='linkedin',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='telegram',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='twitter',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
