# Generated by Django 2.2 on 2020-08-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20200803_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'contact_us', 'verbose_name_plural': 'contact_us'},
        ),
        migrations.AlterField(
            model_name='main',
            name='field1',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='main',
            name='field2',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='main',
            name='field3',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='main',
            name='field4',
            field=models.CharField(max_length=64),
        ),
    ]
