# Generated by Django 2.2 on 2020-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='permission',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
